alias ll='eza -la --group-directories-first --git' || alias ll='ls -alF'
alias la='eza -la --group-directories-first' || alias la='ls -A'
alias l='eza -l --group-directories-first' || alias l='ls -CF'
alias tree='eza --tree' || alias tree='tree'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias gs='git status --short'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit --verbose'
alias gcm='git commit --message'
alias gp='git push'
alias gpl='git pull'
alias gl='git log --oneline --graph --decorate --all'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gd='git diff'
alias gst='git stash'

alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps --all'
alias di='docker images'
alias dprune='docker system prune --all --volumes'
alias dlogs='docker logs --follow'

alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcl='docker-compose logs'

alias pn='pnpm'
alias pni='pnpm install'
alias pna='pnpm add'
alias pnrm='pnpm remove'
alias pnrun='pnpm run'
alias pnd='pnpm run dev'
alias pnb='pnpm run build'

alias reload='exec zsh'
alias zshconfig='$EDITOR ~/.config/zsh'
alias path='echo $PATH | tr ":" "\n"'
alias h='history | grep'
alias top='htop || top'

if command -v bat > /dev/null; then
    alias cat='bat --style=plain'
fi

alias vim='nvim'
alias vi='nvim'
alias v='nvim'